### ISSUE TITLE
Extending the class 'rikudou\SkQrPayment\QrPayment' is deprecated

### ISSUE THREAD

**Issue by Ivorius** [RikudouSage/QrPaymentSK#15]
Proč je rozšíření třídy deprecated? Já si tak např. musel přetížit metodu` getXzBinary()`, aby nekontrolovala existenci souboru  `xzPath`, neboť na hostingu sice je v `/usr/bin/xc` ale přes `file_exists` to neprošlo.

**Comment by RikudouSage** [comment]
Ve verzi 3 bude třída final, tohle je relativně starý kód a verze 3 bude přepis do modernější podoby, kde se bude používat kompozice místo dědění.

**Comment by RikudouSage** [comment]
Přidána možnost použít flag, díky kterému se nekontroluje, jestli ta cesta existuje.
