### ISSUE TITLE
Allow set values back to null

### ISSUE THREAD

**Issue by KacerCZ** [RikudouSage/QrPaymentSK#22]
Properties `variableSymbol`, `specificSymbol`, `constantSymbol`, `dueDate` and `xzPath` have default value `null`.
Their getters allow to return `null` (for symbol properties) or use fallback value.
Their setters don't allow set these properties back to `null`.
Please allow set mentioned properties back to `null` by allowing nullable type in parameters of setters.

**Comment by RikudouSage** [comment]
I'll look into it tonight.

**Comment by KacerCZ** [comment]
I tested the change and it works as expected.
Thank you.
