### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Droutin** [RikudouSage/QrPaymentSK#27]
Prosím o windows support.
Malo by stačiť vytvoriť podmienku po neúspešnom exec('which xz', $output, $return); na windows variantu. exec('where xz', $output, $return);

**Comment by RikudouSage** [comment]
Na to lze použít vlastní lokátor, v podstatě zkopírovat ten český a upravit logiku:

```php
<?php

class WindowsXzLocator implements XzBinaryLocatorInterface
{
    private ?string $path = null;

    public function getXzBinary(): string
    {
        if ($this->path === null) {
            exec('where xz', $output, $return);
            if ($return !== 0) {
                throw new QrPaymentException("'xz' binary not found in PATH, specify it using setXzBinary()");
            }
            if (!isset($output[0])) {
                throw new QrPaymentException("'xz' binary not found in PATH, specify it using setXzBinary()");
            }
            $this->path = $output[0];
        }
        if (!file_exists($this->path)) {
            throw new QrPaymentException("The path '{$this->path}' to 'xz' binary is invalid");
        }

        return $this->path;
    }
}
```

Pokud víte, kde přesně se xz nachází, nemusí to být ani stejná logika, stačí jen vrátit přímo cestu.

Následně:

```php
<?php

$payment->setXzBinaryLocator(new WindowsXzLocator());
```

Pokud by se vám chtělo vytvořit pull request na tento lokátor a logiku pro automatické určení lokátoru podle OS, byl bych vám vděčný, bohužel Windows nemám.

**Comment by gamelaster** [comment]
For me, I just needed to download LZMA Windows build and set xz.exe binary
