### ISSUE TITLE
treat variable/constant/specific symbols as strings

### ISSUE THREAD

**Issue by ttibensky** [RikudouSage/QrPaymentSK#30]
There are symbols with leading zeros, e.g. `0308` https://www.mbank.sk/pomoc/info/ucty/zoznam-najpouzivanejsich-konstantnych-symbolov.html. If you treat it as an integer, the first zero will be ommited resulting in an incorrect symbol `308`.

**Comment by ttibensky** [comment]
Here is a change proposal https://github.com/RikudouSage/QrPaymentSK/pull/31. You would also need to modify the documentation and perhaps do a new major release since this is a breaking change.

**Comment by RikudouSage** [comment]
Released as 4.0.0
