### ISSUE TITLE
Brutus... to XZ jsem vůbec nepochopil

### ISSUE THREAD

**Issue by mzvarik** [RikudouSage/QrPaymentSK#35]
setXzBinary() ....

**Comment by mzvarik** [comment]
OK... asi se musí stáhnout toto: https://www.7-zip.org/sdk.html

**Comment by mzvarik** [comment]
Teď to hlásí... endroid/qr-code not loaded... takže jsem dal: "composer require endroid/qr-code"
Ale pořád to nejde...

**Comment by mzvarik** [comment]
Miluju tyhle knihovny na tisíc řádků, které potřebujou 10 dalších komponent a stejně to nejde.

Tady je jiný funkční skript na 5 řádků 👍
https://jan.fecik.sk/blog/qr-generator-platieb-pay-by-square-v-php/

**Comment by RikudouSage** [comment]
Je potřeba stáhnout xz binárku, https://tukaani.org/xz/xz-5.2.5-windows.zip, na to stačí deset vteřin googlování. V dokumentaci je jasně napsáno, že chcete-li používat metodu pro získání QR obrázku, je potřeba nainstalovat `endroir/qr-code`. Pro příště bych prosil o slušnější vystupování, dělám tuto knihovnu ve volném čase a zadarmo a všichni ostatní ji zjevně použít zvládli, jelikož tohle je první issue na tohle téma, takže problém zjevně nebude v knihovně, ale v uživateli.
