### ISSUE TITLE
Windows don't like ' in proc_open

### ISSUE THREAD

**Issue by gamelaster** [RikudouSage/QrPaymentSK#45]
When using LZMA for Windows, the Windows doesn't like this `${xzBinary} '--format=raw' '--lzma1=lc=3,lp=0,pb=2,dict=128KiB' '-c' '-'`. It treads ' as separate command:
```
php .\test.php
xz: '--format=raw': No such file or directory
xz: '--lzma1=lc=3,lp=0,pb=2,dict=128KiB': No such file or directory
xz: '-c': No such file or directory
xz: '-': No such file or directory
```

After removing ' , everything works just fine. Are they required for some other OS ?

**Comment by RikudouSage** [comment]
It doesn't seem it's needed and it works on Linux.

**Comment by RikudouSage** [comment]
@gamelaster Can you check that the new version works for you on Windows, please?

**Comment by gamelaster** [comment]
Works good for me, thank you for amazing library!
