### ISSUE TITLE
No QR code provider found exception after installing

### ISSUE THREAD

**Issue by kaszarobert** [RikudouSage/QrPaymentSK#49]
I'm using the code from the readme at https://github.com/RikudouSage/QrPaymentSK#getting-the-result and after running `composer require rikudou/skqrpayment` and calling `$payment->getQrImage();` this is what I'm getting:

`
rikudou\SkQrPayment\Exception\QrPaymentException: Error: library endroid/qr-code is not loaded. in rikudou\SkQrPayment\QrPayment->getQrImage() (line 247 of /app/vendor/rikudou/skqrpayment/src/QrPayment.php).
`

I tried adding them manually by running `composer require endroid/qr-code` and `composer require rikudou/qr-payment-qr-code-provider` but the same thing is happening.

I also tried modifying `$payment->getQrImage();` to `$payment->getQrCode();` but another error is happening:

`
Rikudou\QrPaymentQrCodeProvider\Exception\NoProviderFoundException: No QR code provider found. in Rikudou\QrPaymentQrCodeProvider\QrCodeProviderLocator->getProvider() (line 41 of /app/vendor/rikudou/qr-payment-qr-code-provider/src/QrCodeProviderLocator.php).
`

I'm trying to add this to a Drupal 9 site using PHP 7.4. What am I doing wrong?

**Comment by RikudouSage** [comment]
That's really weird and I can't really think of any reason it can be happening except some weird autoloading issues. Are you sure you're installing it in the same composer.json?

It should work out of the box by just installing `endroid/qr-code`.

Can you verify that the package is installed correctly by using `var_dump(interface_exists(\Endroid\QrCode\Writer\Result\ResultInterface::class) || class_exists(\Endroid\QrCode\QrCode::class));` somewhere in your project?

Or if you use step debugger to trace why it happens? Unless you provide me with some project where this happens I'm afraid I cannot debug it.

**Comment by kaszarobert** [comment]
It turned out that I needed to reboot the Apache server to make it work for some reason. After that I had
`Error: library endroid/qr-code is not loaded or is not a 3.x version. For newer versions please use method getQrCode()` error, so I did what the error message advised and finally got it working.

This is the workflow and code that I got it running if others encounter this kind of problem, too:
- `composer require rikudou/skqrpayment endroid/qr-code`
- Used the following code:
```
      use Rikudou\Iban\Iban\IBAN;
      use rikudou\SkQrPayment\QrPayment;

      $payment = new QrPayment(new IBAN($iban));

      $payment
        ->setAmount($amount)
        ->setComment($spravaPrePlatitela)
        ->setConstantSymbol($konstantnySymbol)
        ->setCountry($country)
        ->setCurrency($mena)
        ->setInternalId($documentSerial)
        ->setPayeeAddressLine1($adresa1)
        ->setPayeeAddressLine2($adresa2)
        ->setPayeeName($menoPrijimatela)
        ->setSpecificSymbol($specifickySymbol)
        ->setVariableSymbol($variabilnySymbol)
        ->setXzBinary($xz);

      $payment->getQrString();
      $qrCode = $payment->getQrCode();
      $qrCodeBase64 = base64_encode($qrCode->getRawString());
```

- Display with template like this
`<img src="data:image/png;base64, {{ qrCodeBase64 }}'" alt="PAY by square kód">`
- Reboot dev server if needed.

Because this issue was with my development environment and not this project, I'm closing it.

**Comment by RikudouSage** [comment]
Glad you got it working! Just a side note, you can use `getQrCode()->getDataUri​()` instead of base64 encoding it yourself.
