### ISSUE TITLE
XzBinaryLocator is only for linux host, what abou windows?

### ISSUE THREAD

**Issue by SanoKriss** [RikudouSage/QrPaymentSK#52]
In XzBinaryLocator.php there is on line 22:
`exec('which xz', $output, $return);` 
This should be wrapped to check if php host is linux or windows:
`if (stristr(PHP_OS, 'LINUX')) {
  exec( 'which xz', $output, $return );
} elseif (stristr(PHP_OS, 'WIN')) {
  exec( 'where xz', $output, $return );
 } else {
  throw new QrPaymentException("not supported OS");
 }`

**Comment by RikudouSage** [comment]
As per the documentation:

If you want to implement custom logic for getting the binary path, you can create a custom class implementing \rikudou\SkQrPayment\Xz\XzBinaryLocatorInterface and set the object via setXzBinaryLocator() in the payment object.

You can also create a pull request with the new xz binary locator for Windows.
