### ISSUE TITLE
Master zip neobsahuje priecinok TESTS ani dalsie subory z korenoveho adresara

### ISSUE THREAD

**Issue by fafayqa** [RikudouSage/QrPaymentSK#59]
Jakoze sorry, ale jak sa da toto MANUALNE NAINSTALOVAT?!

Reku, urobim rychly test podla prikladu co tu uvadzas, a jeeeb:

```
use rikudou\SkQrPayment\QrPayment;
use Rikudou\Iban\Iban\IBAN;

$payment = new QrPayment(new IBAN('SK6807200002891987426353'));

$payment
    ->setAmount(500)
    ->setVariableSymbol('123456')
    ->setDueDate(new DateTime('+1 week'))
;

$qrString = $payment->getQrString();

// $qrString now holds the string to embed inside the QR code, in this example:
// 0004U0001M8GLP3E8KPT058IQ99QISMB02IH36MOD4BCKQQGVDE4641AOA2NURPCOPSALFG0LPG1C6N0E2JMC7RG2F4L2E57OCSHOUROGHOC8VTTPHHRFHU6VFTM8N80

$qrCode = $payment->getQrImage();

// send to browser
header('Content-Type: ' . $qrCode->getContentType());
echo $qrCode->writeString();
```

**Fatal error: Class 'rikudou\SkQrPayment\QrPayment' not found in Z:\_SERVER_\root\www\...\index.php on line 108**

Boha, preco nemozes spravit BEZNY NORMALNY SPOSOB IMPLEMENTACIE JAK VACSINA NORMNALNYCH KODEROV, al epouzijes PREIJEBANE `use`??? Nejake include/require - nic, ee, vobec?! Neee, ty radsej vymyslis NEPOCHOPITELNY SPOSOB...cele zle, a take nadejne to s tebou bolo, skoda!

Toto jednoducho priemerne zdatny clovek nema sancu pochopit, lebo implementacia MANUALNA nie je nikde uvedena!!!! `composer require rikudou/skqrpayment` si strc vies kam...nepouzitelne, nepouzivam ziadny prijebany redakcny system, kurwa!

**Comment by RikudouSage** [comment]
Tahle knihovna tím pádem zjevně není pro tebe.
