### ISSUE TITLE
Getting the result - not working

### ISSUE THREAD

**Issue by fafayqa** [RikudouSage/QrPaymentSK#60]
```
<?php

use rikudou\SkQrPayment\QrPayment;
use Rikudou\Iban\Iban\IBAN;

$payment = new QrPayment(new IBAN('SK6807200002891987426353'));

$payment
    ->setAmount(500)
    ->setVariableSymbol('123456')
    ->setDueDate(new DateTime('+1 week'))
;

$qrString = $payment->getQrString();

// $qrString now holds the string to embed inside the QR code, in this example:
// 0004U0001M8GLP3E8KPT058IQ99QISMB02IH36MOD4BCKQQGVDE4641AOA2NURPCOPSALFG0LPG1C6N0E2JMC7RG2F4L2E57OCSHOUROGHOC8VTTPHHRFHU6VFTM8N80

$qrCode = $payment->getQrImage();

// send to browser
header('Content-Type: ' . $qrCode->getContentType());
echo $qrCode->writeString();
```

Testing on local testserver with PHP 8.1 in PC (Win10 x64): as soon as the code reaches `$qrString = $payment->getQrString();` it quits with webpage page saying: 

**_This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500_**

Installed with `php composer.phar update --no-cache --with-all-dependencies`

UPDATE
Tested a bit more: in the public function `getQrString()` the problem starts with the line `$xzBinary = $this->getXzBinary();`. As soon as it reaches this line, code breaks and all stops.

Now I do understood I need something called "xz binary" and set its path in the options for `$payment` using `->setXzBinary('/path/to/xz')`. On Wikipedia I find those are "XZ Utils (previously LZMA Utils) is a set of [free software](https://en.wikipedia.org/wiki/Free_software) [command-line](https://en.wikipedia.org/wiki/Command-line_interface) [lossless data compressors](https://en.wikipedia.org/wiki/Lossless_compression), including the programs lzma and xz, for [Unix-like](https://en.wikipedia.org/wiki/Unix-like) operating systems and, from version 5.0 onwards, [Microsoft Windows](https://en.wikipedia.org/wiki/Microsoft_Windows)."

**QUESTION IS:** where to get those XZ binaries??? I found one here: https://tukaani.org/xz/xz-5.2.9-windows.7z
I did extract those to root "xz" folder, I set `->setXzBinary('/xz')` but it still does not work.

Ah, I see: correct path shout start without the `/`, so that it is ` ->setXzBinary('xz')` - now it passed!

**YOU CAN SET THIS ISSUE AS SOLVED NOW...**

**Comment by RikudouSage** [comment]
Glad you could solve it! In general, on Windows absolute paths start with the drive letter, so for example `C:\\path\\to\\xz.exe`. You can also use paths relative to your script as you discovered. In general, for development I recommend turning on some kind of error reporting.
