### ISSUE TITLE
Doesn't work with endroid/qr-code v6.0

### ISSUE THREAD

**Issue by krtcom** [RikudouSage/QrPaymentSK#62]
versions from package.json:
```
"endroid/qr-code": "^6.0",
"rikudou/skqrpayment": "^4.2",
```
Then calling `$payment->getQrCode();` causes error

**Call to undefined method Endroid\QrCode\QrCode::create() at [hidden]/vendor/rikudou/qr-payment-qr-code-provider/src/EndroidQrCode4Provider.php:13)**

example code:
```
$payment = new QrPayment(new IBAN($iban));
$payment->setOptions([
    QrPaymentOptions::AMOUNT => $amount,
    QrPaymentOptions::CONSTANT_SYMBOL => $constSymbol,
    QrPaymentOptions::VARIABLE_SYMBOL => $variableSymbol,
    QrPaymentOptions::XZ_PATH => '/usr/bin/xz',
]);

$qrCode = $payment->getQrCode();
```

When downgraded to endroid/qr-code 5.8 it works

**Comment by RikudouSage** [comment]
Fixed in https://github.com/RikudouSage/QrPaymentQrCodeProvider/pull/2, after updating that package, it should work.
